CREATE DATABASE InventarioCAM;

CREATE TABLE Equipamento(id INT NOT NULL AUTO_INCREMENT, nome VARCHAR(255), ip VARCHAR(16), PRIMARY KEY(id));

CREATE TABLE Permissao(id INT NOT NULL AUTO_INCREMENT, tipo VARCHAR(100), PRIMARY KEY(id));

CREATE TABLE Usuario(id INT NOT NULL AUTO_INCREMENT, email VARCHAR(150), senha VARCHAR(255), fk_permissao INT, PRIMARY KEY(id), FOREIGN KEY (fk_permissao) REFERENCES Permissao(id));