# Generated by Django 2.1.1 on 2018-09-11 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20180911_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissao',
            name='tipo',
            field=models.CharField(max_length=45),
        ),
    ]
