# Generated by Django 2.1.1 on 2018-09-14 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20180911_1203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='fkpermissao',
            new_name='permissao',
        ),
    ]
