# Generated by Django 2.1.1 on 2018-09-11 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=35)),
                ('nome', models.CharField(max_length=255)),
                ('versao', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoComponente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=45)),
            ],
        ),
        migrations.AddField(
            model_name='componente',
            name='fkpermissao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='componentes.TipoComponente'),
        ),
    ]
