# Generated by Django 2.0.5 on 2018-09-17 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('componentes', '0002_auto_20180914_1652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='componente',
            old_name='permissao',
            new_name='tipo',
        ),
    ]
