# Generated by Django 2.1.1 on 2018-09-11 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=35)),
                ('nome', models.CharField(max_length=255)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('website', models.CharField(blank=True, max_length=50, null=True)),
                ('idEstatistica', models.CharField(blank=True, max_length=45, null=True)),
                ('cep', models.CharField(blank=True, max_length=10, null=True)),
                ('logradouro', models.CharField(blank=True, max_length=100, null=True)),
                ('num', models.CharField(blank=True, max_length=7, null=True)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('bairro', models.CharField(blank=True, max_length=55, null=True)),
                ('estado', models.CharField(blank=True, max_length=2, null=True)),
                ('cidade', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=35)),
                ('nome', models.CharField(max_length=255)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('website', models.CharField(blank=True, max_length=50, null=True)),
                ('servidor', models.CharField(blank=True, max_length=20, null=True)),
                ('logradouro', models.CharField(blank=True, max_length=100, null=True)),
                ('num', models.CharField(blank=True, max_length=7, null=True)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('bairro', models.CharField(blank=True, max_length=55, null=True)),
                ('estado', models.CharField(blank=True, max_length=2, null=True)),
                ('cidade', models.CharField(blank=True, max_length=45, null=True)),
                ('posicaogeo', models.CharField(blank=True, max_length=85, null=True)),
                ('fkinstituicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instituicoes.Instituicao')),
            ],
        ),
    ]
