# Generated by Django 2.1.1 on 2018-09-11 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0001_initial'),
        ('instituicoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instituicao',
            name='contatos',
            field=models.ManyToManyField(blank=True, to='contatos.Contato'),
        ),
        migrations.AddField(
            model_name='unidade',
            name='contatos',
            field=models.ManyToManyField(blank=True, to='contatos.Contato'),
        ),
    ]
