# Generated by Django 2.1.1 on 2018-09-14 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instituicoes', '0002_auto_20180911_1423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unidade',
            old_name='fkinstituicao',
            new_name='instituicao',
        ),
    ]
