# Generated by Django 2.1.1 on 2018-09-21 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0003_anotacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivo',
            name='atualizado',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='core',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='web',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='anotacao',
            name='nota',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='ipvirtual',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
