# Generated by Django 2.1.1 on 2018-09-25 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0004_auto_20180921_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='ip',
            field=models.CharField(max_length=25),
        ),
    ]
